apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ns1
  namespace: ns1
  labels:
    app: deploy-ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-ns1
  template:
    metadata:
      labels:
        app: deploy-ns1
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
