apiVersion: v1
kind: Service
metadata:
  name: svc-ns1
  namespace: ns1
  labels:
    app: deploy-ns1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: deploy-ns1
