apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: learner-csr
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1Z6Q0NBVDhDQVFBd0VqRVFNQTRHQTFVRUF3d0hiR1ZoY201bGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMM3V6emxkVWpoMmFjRzI1MElMUXZjQWYxYzY4MlhlaDhYcnRsUXp0VHVHCjdrS3BaTTAzTUE0N2MwWVVsREN5djJmUE0yWUhOVWxBZHlldG10V3hmcHpXazV4T0NwbS9yN3haenV5anFoVlQKUUtGdGp5WmNDc2tNVlhNV1ZUa1VSczV4TFAzRkF6Z2ZkdXZnZ2ExUmhQYUVXNU5od0gwbG0zb1o4UXQvSlV3VQpMMzcvZjNhOXdudlAvRDVUcTFFUk9KMmRua1RQMGlxOGpTRk56NUpnMWE2WkZTUHZ3QzRZOUlYQXVQODJtTUFtCjkxSTYrUXh1NWE3b1daSFJCcHFrYXZTQisyNU4vZTBIRkh2TDd2cjFmSUt0VE1hdDRkUGVrYVVnUXM3VUtxS08KVm12bDhyRkQ0anlzRUVqTkd0Q2RaNTVQS09jZFRqcEVXMVFDZGppYjE2MENBd0VBQWFBQU1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUIxREhFeTJsd3pGTXVmdm1ONTdOMEFrd1lrWnF5aHJLckdYZVAyWndqVkcrZVpxTlNnClF0ZkxGalNOOGkvOTFHb2tIY0F5QkRvbXZ4d3QwWVYxTTBCZlBRWnIzRWNEd2pIQ2dVU25IVVg5OUpSMGsxczkKcjBqNDBjWStMQy9HeTErZGZSMjdhdlNVVUxqSldGTllLdTlxcXA5dnBObCtmTGRpZFA0TitBZDVNR2ZsQVJadApuaUd2M0ZFN1B2U1Ara0RJNThLYVdrcDlxc3BKUW54SFV6UXBRMXpWY01ndTVhS25LdTEzWEFqN3VhVllUeWwwCnVyRFNVOUo4ZXZZOFhqSWdmdWNQeUdJNnRrOEl2bGZUVitkSFFOYk5sM3F1U012YzFPeWxIZG9hdVFXTm52cmMKYnN6eXkyVEFzWkhRbTFQOHpyQkJNOUozcWs5dEJLWUpUbEQ5Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400   # 1 day (optional)
  usages:
  - client auth

