apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
  labels:
    env: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx

